server:
  port: 8090

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:schoolquery
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  cloud:
    stream:
      defaultBinder: rabbit1
      binding:
        school-input-events:
          destination: school-events
          group: school-query
      rabbit:
        bindings:
          school-input-events:
            consumer:
              exchange-type: fanout
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: rodrigo
                password: carrico_