INSERT INTO Professor (ID, CPF, NOME, EMAIL, TITULACAO) VALUES('1234','0000000000','RODRIGO','teste@teste.com.br','MESTRE');

INSERT INTO Disciplina(ID,CARGA_HORARIA, DESCRICAO, SIGLA, PROFESSOR_ID) VALUES('1',100, 'MATEMATICA','M','1234')